name: News Scheduler

on:
  schedule:
    # 1:07 AM UTC = 9:07 AM PH (Using an off-peak minute for better reliability)
    - cron: "7 1 * * *" 
  workflow_dispatch: 

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Call API
        run: |
          curl -X GET https://newsbot-vert.vercel.app/api/fetch
